var projectInfo = [
  {title: "Singles",
   image: "media/attack-on-saturn.png",
   audioPath: "audio/starburn/",
   details: ""},
  {title: "Dear Clarent Songbook",
   imagePath: "media/dear-clarent-songbook.png",
   audioPath: "audio/",
   details: ""},
  {title: "Little Guy, Big Sword",
   imagePath: "media/little-guy-big-sword.jpg",
   audioPath: "audio/little-guy-big-sword/",
   details: ""},
  {title: "Kindled Core",
   imagePath: "media/kindled-core.png",
   audioPath: "audio/kindled-core/",
   details: ""},
  {title: "Haunted House",
   imagePath: "media/haunted-house.png",
   audioPath: "audio/starburn/",
   details: ""},
];

var musicList = [
  {title: "Attack On Saturn",
   songId: "s1",
   projectIndex: 0,
   songFile: ""},
  
  {title: "Enoument",
   songId: "dc1",
   projectIndex: 1,
   songFile: "Seawright Line Songbook Audio Mixing - 10-énoument.wav (1).wav"},
  {title: "Birth And Beloiter",
   songId: "dc2",
   projectIndex: 1,
   songFile: "Seawright Line Songbook Audio Mixing - 9-birth-and-beloiter.wav (1).wav"},
  {title: "Ruckkehrunruhe",
   songId: "dc3",
   projectIndex: 1,
   songFile: "Seawright Line Songbook Audio Mixing - 4-rückkehrunruhe.wav (1).wav"},

  {title: "Journey Start",
   songId: "lgbs1",
   projectIndex: 2,
   songFile: "journey-start.mp3"},
  {title: "Into the Pit",
   songId: "lgbs2",
   projectIndex: 2,
   songFile: "into-the-pit.mp3"},
  {title: "Second Chances",
   songId: "lgbs3",
   projectIndex: 2,
   songFile: "second-chances.mp3"},
  {title: "Waiting Arena",
   songId: "lgbs4",
   projectIndex: 2,
   songFile: "waiting-arena.mp3"},
  {title: "The Rooster",
   songId: "lgbs5",
   projectIndex: 2,
   songFile: "the-rooster.mp3"},
  {title: "You Did It!!",
   songId: "lgbs6",
   projectIndex: 2,
   songFile: "you-did-it.mp3"},

  {title: "Intro Theme",
   songId: "kc1",
   projectIndex: 3,
   songFile: "intro-theme.mp3"},
  {title: "The Hollow Winter",
   songId: "kc2",
   projectIndex: 3,
   songFile: "hollow-winter.mp3"},
  {title: "House Theme",
   songId: "kc3",
   projectIndex: 3,
   songFile: "house-theme.mp3"},
  {title: "City Theme",
   songId: "kc4",
   projectIndex: 3,
   songFile: "city-theme.mp3"},
  
  {title: "Haunted House",
   songId: "s2",
   projectIndex: 4,
   songFile: "haunted-house.mp3"}
  
];
  
  
// "kc1","kc2","kc3","lgbs1","lgbs2","lgbs3","lgbs4","lgbs5","lgbs6","dc1","dc2","dc3","s1"
  
